from app.cura import db
import datetime
from sqlalchemy.dialects.postgresql import JSONB
class Vehicle(db.Model):
    __tablename__ = "tbl_vehicle"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    public_id = db.Column(db.String(255), nullable=False)
    model =  db.Column(db.String(255), nullable=True)
    commissioned_date = db.Column(db.DateTime, nullable=True)
    regn_date = db.Column(db.DateTime, nullable=True)
    chassis_no = db.Column(db.String(255), nullable=True)
    regn_no = db.Column(db.String(255), nullable=True)
    engine_no = db.Column(db.String(255), nullable=True)
    engine_capacity = db.Column(db.String(255), nullable=True)
    engine_fuel_type = db.Column(db.String(255), nullable=True)
    trailer_regn = db.Column(db.String(255), nullable=True)
    trailer_model = db.Column(db.String(255), nullable=True)
    trailer_type =  db.Column(db.String(255), nullable=True)
    weight_category_bdm =  db.Column(db.String(255), nullable=True)
    weight_category_btm = db.Column(db.String(255), nullable=True)
    weight_category_bt1 = db.Column(db.String(255), nullable=True)
    ld_road_tax = db.Column(db.String(255), nullable=True)
    ld_puspakom = db.Column(db.String(255), nullable=True)
    ld_insurance = db.Column(db.String(255), nullable=True)
    pump_fitted = db.Column(db.Integer, nullable=True)
    top_loading = db.Column(db.Integer, nullable=True)
    pto_equip = db.Column(db.Integer, nullable=True)
    bottom_load = db.Column(db.Integer, nullable=True)
    vehicle_category = db.Column(db.String(255), nullable=True)
    vehicle_remark = db.Column(db.String(500), nullable=True)
    vehicle_depoh = db.Column(db.String(255), nullable=True)
    location = db.Column(db.String(255), nullable=True)
    client_name = db.Column(db.String(255), nullable=True)
    color_scheme = db.Column(db.String(255), nullable=True)
    front = db.Column(db.String(255), nullable=True)
    rear = db.Column(db.String(255), nullable=True)
    starboard = db.Column(db.String(255), nullable=True)
    port = db.Column(db.String(255), nullable=True)
    created_by = db.Column(db.Integer, nullable=True)
    updated_by = db.Column(db.Integer, nullable=True)
    created_date = db.Column(db.DateTime, nullable=True, default=datetime.datetime.utcnow())
    updated_date = db.Column(db.DateTime, nullable=True, default=datetime.datetime.utcnow())
    isActive = db.Column(db.Integer, nullable=True, default=1)